[build]
    publish = "public"
    command = "# No build command"

[[redirects]]
    from = "/hex/:color"
    to = "/.netlify/builders/color"
    status = 200
    force = true

[[redirects]]
    from = "/rgb/:r/:g/:b"
    to = "/.netlify/builders/color"
    status = 200
    force = true

[[redirects]]
    from = "/named/:color"
    to = "/.netlify/builders/color"
    status = 200
    force = true
